#!/bin/bash
set -euo pipefail

usage() {
    cat >&2 <<EOM
usage: $(basename "$0") IMAGE_PATH [EMOJI_NAME]

Upload custom emoji to Slack.

This script uses the normal user token that you can export out of a browser by
using the browser network inspector and exporting a request as curl.

You must set SLACK_TOKEN and SLACK_COOKIE in the environment.

    SLACK_TOKEN comes from the multipart form data, and starts with "xoxc-"

    SLACK_COOKIE comes from the cookie header. We only need the cookie that
    starts with "d=xoxd-", but feel free to copy in the entire cookie header
    value. This should be URL % encoded.

EOM
}


run() {
    echo >&2 "+ $*"
    "$@"
}

if [ -z "${SLACK_TOKEN-}" ] || [ -z "${SLACK_COOKIE-}" ]; then
    echo >&2 "Please set env vars:"
    echo >&2 "  SLACK_TOKEN=xoxc-..."
    echo >&2 "  SLACK_COOKIE='d=xoxd-...'"
    exit 1
fi

case $# in
    1)
        image_path="$1"
        emoji_name="$(basename "$image_path")"
        emoji_name="${emoji_name%.*}" # strip extension
        ;;
    2)
        image_path="$1"
        emoji_name="$2"
        ;;
    *)
        usage
        exit 1
        ;;
esac

curl_opts=
if [ -n "${DEBUG-}" ]; then
    curl_opts=-v
fi

run curl $curl_opts -sSf -X POST \
    "https://slack.com/api/emoji.add" \
    -H 'content-type: multipart/form-data' \
    -H "cookie: $SLACK_COOKIE" \
    -F "token=$SLACK_TOKEN" \
    -F mode=data \
    -F name="$emoji_name" \
    -F image=@"$image_path"
echo
